packages/server/mailing/ftp-client.service.js, packages/server/mailing/mailing.service.js
Fix Relative path to the images
https://github.com/Badsender-com/LePatron.email/issues/429
=> Fix sftp problem

.eslintrc.js, README.md, jest.config.js, package.json, packages/server/account/roles.test.js, yarn.lock
- To be able to write units tests so we make sure every bug detected is tested and cannot be on the project again
- To be able to see regression
- To be able to create a CI that will run tests and block the merge if some tests are failing
=> feat: add jest config and test example file

packages/server/group/group.schema.js, packages/server/utils/crpyto.js
Add password encryption for admin
=> Add password encryption for ftp admin

package.json, packages/editor/src/js/vue/components/esp/esp-send-mail.js, packages/editor/src/js/vue/components/esp/providers/ActitoComponent.js, packages/server/esp/actito/actitoProvider.js, packages/server/mailing/ftp-client.service.js, packages/server/profile/profile.service.js, public/lang/badsender-en.js, public/lang/badsender-fr.js, yarn.lock
https://github.com/Badsender-com/LePatron.email/issues/409
=> Feat add actito component editor

packages/server/mailing/mailing.schema.js, packages/server/mailing/mailing.service.js, packages/server/utils/model.js
Add hasPreviewHtml property  based on previewHtml existence for mailings listing API, this will be helpfull for the download multiple feature
=> Add hasPreviewHtml property 

packages/editor/src/js/ext/badsender-server-storage.js, packages/server/mailing/mailing.schema.js
Fix editor save and back button 
https://user-images.githubusercontent.com/80390318/130928283-f5de84df-140c-48c6-ba1a-4968ad6be9c4.mp4
=> fix editor back and save button

.eslintignore, packages/editor/src/js/vue/components/esp/esp-send-mail.js, packages/editor/src/js/vue/components/esp/profile-list.js, packages/editor/src/js/vue/components/esp/providers/ActitoComponent.js, packages/editor/src/js/vue/components/esp/providers/SendinBlueComponent.js, packages/editor/src/js/vue/constant/esp-type.js, packages/editor/src/js/vue/constant/send-mode.js, packages/editor/src/js/vue/vuePlugin.js, packages/server/mailing/mailing.schema.js, packages/server/routes-oauth2.js, packages/server/user/user.controller.js
- Fix linter vue errors in the editor
- Remove useless console.logs
=> Fix linter errors

packages/editor/src/css/badsender-topbar.less
=> Add scroll in editor esp listings

packages/server/emails-group/emails-group.service.js, packages/server/mailing/mailing.service.js, packages/ui/routes/mailings/__partials/mailings-table.vue, packages/ui/routes/mailings/index.vue
- configure method to control if we upload image sync/async related to https://github.com/Badsender-com/LePatron.email/issues/324
- Remove useless console.log
- Fix bug when downloading single ftp file doesn't work related to https://github.com/Badsender-com/LePatron.email/issues/324
=> Add possibility to wait or not for the ftp upload depending on the usecase

packages/editor/src/css/badesender-image-gallery.less
Related to : https://github.com/Badsender-com/LePatron.email/issues/452
=> Fix style the white writing for the upload image modal in the tabs section

packages/server/group/group.routes.js, public/lang/badsender-en.js, public/lang/badsender-fr.js
- Fix placeholder wording for emails test inputs
=> Fix permission for regular user

packages/editor/src/js/ext/badsender-server-storage.js, packages/server/mailing/mailing.controller.js, packages/server/mailing/mailing.schema.js, packages/server/mailing/mosaico-editor.controller.js
https://github.com/Badsender-com/LePatron.email/issues/407
- Fix the save mail bug ( previously email didn't change after we save it )
- Remove redirection after saving the mail
- Redirection user role admin to group information
- Redirect user role Group admin and regular user to group informations
=> Fix saving mail bug + redirect mail

packages/editor/src/js/vue/components/esp/providers/ActitoComponent.js, packages/server/esp/actito/actitoProvider.js
Fix issue https://github.com/Badsender-com/LePatron.email/issues/487
- Allow user to use special caractere in the esp actito mail name
=> Fix allow special caractere in mail

packages/ui/helpers/locales/fr.js, public/lang/badsender-fr.js
=> Fix wording test group

packages/editor/src/js/vue/components/esp/esp-send-mail.js, packages/editor/src/js/vue/components/esp/providers/DscComponent.js, packages/editor/src/js/vue/components/esp/providers/SendinBlueComponent.js, packages/server/esp/dsc/dscProvider.js
- Add send mail form to DSC esp
- Add edit mail  feature to DSC esp
=> Add sent campaign form to editor

package.json, packages/server/esp/dsc/dscProvider.js, yarn.lock
Fix proxy connection by adding the lib HttpsProxyAgent
=> Fix proxy connection

package.json, packages/editor/src/css/badsender-editor.less, packages/editor/src/js/vue/components/esp/esp-send-mail.js, packages/editor/src/js/vue/components/esp/providers/DscComponent.js, packages/editor/src/js/vue/components/select/selectComponent.js, packages/editor/src/js/vue/components/send-test/test-modal.js, packages/editor/src/js/vue/components/time-input/timeInput.js, packages/editor/src/js/vue/constant/esp-type.js, packages/editor/src/js/vue/vuePlugin.js, packages/server/esp/dsc/dscProvider.js, packages/server/profile/profile.service.js, public/lang/badsender-en.js, yarn.lock
- add time input clarification field to send campaign mail form to ESP
=> Add timepicker planification

packages/server/esp/dsc/dscProvider.js
Fix time not mandatory when sending or editing already sent Mail to DSC provider
=> Fix time not mandatory

packages/server/mailing/mailing.schema.js, packages/server/mailing/mailing.service.js
Related issue: https://github.com/Badsender-com/LePatron.email/issues/572
Remove duplication of ESP connectors relation when we copy a mail
=> Fix mail duplication

packages/ui/components/profiles/esp/ACTITOComponent.vue, packages/ui/components/profiles/esp/DSCComponent.vue
Related issue [580](https://github.com/Badsender-com/LePatron.email/issues/580)
Fix style for DSC form
=> Fix(580) form style for DSC

packages/ui/routes/mailings/__partials/folder-move-modal.vue, packages/ui/routes/mailings/__partials/folder-new-modal.vue, packages/ui/routes/mailings/__partials/mailings-breadcrumbs.vue, packages/ui/routes/mailings/__partials/mailings-copy-modal.vue, packages/ui/routes/mailings/__partials/mailings-move-modal.vue, packages/ui/routes/mailings/__partials/mailings-table.vue, packages/ui/routes/mailings/__partials/workspace-tree.vue, packages/ui/routes/mailings/index.vue, packages/ui/store/folder.js, packages/ui/utils/workspaces.js
Related issue https://github.com/Badsender-com/LePatron.email/issues/588
Content:
=> Add feature generate folder from menu

packages/editor/src/js/vue/components/select/selectComponent.js, packages/editor/src/js/vue/components/send-test/test-modal.js, packages/ui/plugins/vue-i18n.js
Related issue [582](https://github.com/Badsender-com/LePatron.email/issues/582)
- Fix select not showing for send test mail
- Remove error in console for app.i18n
=> Fix(582) select not showing in editor

nuxt.config.js, packages/ui/plugins/vue-i18n.js
Fix related issue [581](https://github.com/Badsender-com/LePatron.email/issues/581)
=> Fix(581) trads + fix style colorpicker

packages/ui/routes/mailings/index.vue
Fix related issue (https://github.com/Badsender-com/LePatron.email/issues/590)
=> Fix(590) Mails keep selected after changing location

packages/ui/routes/groups/_groupId/index.vue
Fix related issue https://github.com/Badsender-com/LePatron.email/issues/601
=> Fix(601) underline style for settings tabs

nuxt.config.js, packages/server/helpers/server-simple-i18n.js, packages/ui/routes/mailings/__partials/folder-move-modal.vue, packages/ui/routes/mailings/__partials/workspace-tree.vue
Fix related issue https://github.com/Badsender-com/LePatron.email/issues/609
=> Fix(609) move folder bug + fix authorites move folders + fix wording

packages/server/config/axios.js, packages/server/esp/dsc/dscProvider.js
Fix issue https://github.com/Badsender-com/LePatron.email/issues/620
Add encodeUri to url before sending the request
=> Fix 620 dsc bug

packages/server/template/generate-preview.controller.js, packages/ui/components/template/menu.vue, packages/ui/routes/templates/_templateId.vue, packages/ui/store/user.js
[Change header params orders](https://github.com/Badsender-com/LePatron.email/commit/87450060fc31772a2bd4632e0dd0a8fb96179d7f)
[Add second Fix for keeping connection event generation template](https://github.com/Badsender-com/LePatron.email/commit/840ffe345781ae5b4f25207b94bf18d5ba3b6dea)
[Add Fix for keeping connection event generation template](https://github.com/Badsender-com/LePatron.email/commit/5a8f8e0689e508a5384137701fb9fb4ccc34b4ef)
[Fix template generation](https://github.com/Badsender-com/LePatron.email/commit/12a2cdd220e7be180cf45f726555f25a26974ff2)
[Fix image template generation](https://github.com/Badsender-com/LePatron.email/commit/2ad6d073de115cccb0314da33f08cae9c775c514)
=> Revert commit after DSC fix

packages/server/esp/dsc/dscProvider.js, packages/server/esp/sendinblue/sendinBlueProvider.js, packages/server/mailing/mailing.service.js
Issue: https://github.com/Badsender-com/LePatron.email/issues/637
Change upload behavior from syncto async when sending DSC or SendinBlue mail
=> Fix async call for DSC and SendinBlue

packages/server/mailing/mailing.service.js
Related to this issue https://github.com/Badsender-com/LePatron.email/issues/649
=> Fix 649: remove duplicate images

packages/server/mailing/mailing.service.js
First image is without data-raw attribute and second one with the attribute.
=> Fix data raw feature

packages/server/utils/download-zip-markdown.js
=> Reduce image name length

packages/editor/src/js/ext/tinymce/tinymce-extend-functions.js, packages/editor/src/js/ext/utils/tinymce-config.js, packages/ui/helpers/locales/en.js, packages/ui/helpers/locales/fr.js, packages/ui/routes/groups/_groupId/index.vue
#716 
Result
https://github.com/Badsender-com/LePatron.email/assets/80390318/d270402a-8e66-4897-9401-b151744c33ad
=> Personalized variable improving UX

packages/editor/src/js/vue/components/save-block-modal/save-modal.js, packages/editor/src/js/vue/utils/apis.js, public/lang/badsender-en.js, public/lang/badsender-fr.js
This feature will enable the saving of a customized block in the application. When a user confirms in the modal, the application will make a POST request to create a personalized block.
1. **Access the GroupId within the Vue Component**:
- Path: File where the save block modal is defined (e.g., `save-block-modal.js`).
- Task:
- Retrieve the `groupId` within the component using `this.vm?.metadata?.groupId`.
2. **Define a Function for the Create Personalized Block Endpoint**:
- Path: File where the service methods are defined (e.g., `apis.js`).
- Task:
- Define a function to return the API endpoint for creating a personalized block.
- The function should accept parameters including name, category (optional), content, and groupId.
3. **Implement the Save Block Method in the Component**:
- …
=> Feat connect create personnalized block

packages/editor/src/js/ext/utils/tinymce-config.js
Remove align option from the EDITOR
=> fix remove align option

packages/editor/src/js/vue/components/personalized-blocks-list/personalized-blocks-list-component.js
=> fix the search input api call

packages/editor/src/js/vue/components/delete-block-modal/delete.modal.js
=> delete block fix

packages/ui/components/mailings/admin-table.vue, packages/ui/routes/users/_userId.vue
https://github.com/Badsender-com/LePatron.email/issues/772
https://github.com/Badsender-com/LePatron.email/assets/80390318/4d9b3f89-9556-4a99-b33c-f32f1f914fdb
=> fix charging mailings edit user page

packages/server/folder/folder.controller.js, packages/server/folder/folder.routes.js, packages/server/folder/folder.service.js, packages/ui/helpers/api-routes.js, packages/ui/routes/mailings/__partials/folder-delete-modal.vue
https://github.com/orgs/Badsender-com/projects/2/views/1?pane=issue&itemId=54772261
https://github.com/Badsender-com/LePatron.email/assets/80390318/b9b33d53-ff27-4359-8901-fcec73bb6604
=> confirm delete folder always and remove time waiting

packages/server/group/group.controller.js, packages/server/mailing/mailing.schema.js, packages/server/node.config.js, packages/server/template/template.schema.js, packages/server/user/user.controller.js, packages/ui/components/group/mailings-tab.vue, packages/ui/components/mailings/admin-table.vue, packages/ui/components/templates/table.vue
The goal of this feature is to implement server-side pagination for mailings to improve performance and reduce the load on the client side. The current system retrieves all mailings at once, which is inefficient for large datasets.
1. **Modify Mailings Fetch Endpoint**:
- **File**: `mailings-controller.js`
- **Task**:
- Update the `readMailings` function to accept `page` and `limit` parameters from the query string.
- Use these parameters to fetch mailings with pagination from the database using `.skip()` and `.limit()` methods.
2. **Return Pagination Info**:
- **File**: `mailings-controller.js`
- **Task**:
- Along with mailings data, return additional pagination details such as `currentPage`, `totalPages`, and `totalMailings`.
1. **Update API Call in Vue Component**:
- **File**: …
=> Add paginations for mailings and optimise requests

packages/server/user/user.controller.js, packages/ui/routes/users/_userId.vue
https://github.com/Badsender-com/LePatron.email/assets/80390318/bf112825-b607-4fbe-aebb-0f6e79165bb0
=> fix pagination for user details

packages/server/template/template.schema.js
https://github.com/Badsender-com/LePatron.email/assets/80390318/3b491f3f-d4da-447b-ac98-6d741e50c3fc
=> fix api templates

packages/server/mailing/mailing.controller.js, packages/server/mailing/mailing.service.js, packages/ui/routes/mailings/__partials/mailings-filters.vue
Remove tags call when charging mails
=> Disable tags call and filter in mailings-filters.vue component

packages/server/mailing/mailing.controller.js, packages/server/mailing/mailing.service.js, packages/ui/routes/mailings/__partials/mailings-filters.vue
Reverts Badsender-com/LePatron.email#808
=> Revert "Disable tags call and filter in mailings-filters.vue component"

packages/editor/src/css/badsender-editor.less, packages/editor/src/js/vue/components/esp/providers/AdobeComponent.js, packages/server/esp/adobe/adobeProvider.js, packages/server/profile/profile.controller.js, packages/server/profile/profile.routes.js, packages/server/profile/profile.service.js, public/lang/badsender-en.js, public/lang/badsender-fr.js
=> feat: adobe delivery select tree

packages/editor/src/css/badsender-editor.less, packages/editor/src/js/vue/components/esp/providers/AdobeComponent.js, public/lang/badsender-en.js, public/lang/badsender-fr.js
* feat: improve export loading ui
* feat: beforeunload event & ui improvement
=> Release staging

packages/server/constant/adobe-target-types.js, packages/server/esp/adobe/adobeProvider.js, packages/server/esp/esp.service.js, packages/server/profile/profile.controller.js, packages/server/profile/profile.schema.js, packages/server/profile/profile.service.js, packages/ui/components/profiles/esp/ADOBEComponent.vue, packages/ui/helpers/constants/adobe-target-types.js, packages/ui/helpers/locales/en.js, packages/ui/helpers/locales/fr.js, packages/ui/routes/groups/_groupId/profiles/_profileId.vue
=> feat: handle delivery and template
